name: publish
on:
  push:
    branches: 
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸš€
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      - name: Setup Node ğŸ›³ï¸
        # Setup node environment
        uses: actions/setup-node@v3
        with:
          # Node version. Run "node -v" to check the latest version
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies ğŸ‘·
        run: npm -v && npm install

      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Publish ğŸ—ï¸
        run: npm publish

        env:
          # We need this to our NPM account
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}